nelmio_security:
    csp:
        enabled: true

        # Ne pas générer les en-têtes de support obsolètes
        compat_headers: false

        report:
            report-uri: "/csp-report"   # active le mode report-only

        # Hash plutôt que 'unsafe-inline'
        hash:
            algorithm: sha256

        enforce:
            default-src:
                - "'self'"
            script-src:
                - "'self'"
                - "https://cdn.jsdelivr.net"
                - "https://www.clarity.ms"
                - "https://buttons.github.io"
                - "https://www.google.com"
                - "https://code.jquery.com"
                - "https://cdn.quilljs.com"
                - "'unsafe-inline'"
            style-src:
                - "'self'"
                - "https://cdn.jsdelivr.net"
                - "https://cdnjs.cloudflare.com"
                - "https://fonts.googleapis.com"
                - "https://cdn.quilljs.com"
                - "'unsafe-inline'"
            font-src:
                - "'self'"
                - "data:"
                - "https://fonts.gstatic.com"
                - "https://cdnjs.cloudflare.com"
            img-src:
                - "'self'"
                - "data:"
            frame-src:
                - "https://www.google.com"
            object-src:
                - "'none'"
            base-uri:
                - "'self'"
            frame-ancestors:
                - "'none'"

    # prevents framing of the entire site
    clickjacking:
        paths:
            '^/.*': DENY

    # disables content type sniffing for script resources
    content_type:
        nosniff: true

    # Send a full URL in the `Referer` header when performing a same-origin request,
    # only send the origin of the document to secure destination (HTTPS->HTTPS),
    # and send no header to a less secure destination (HTTPS->HTTP).
    # If `strict-origin-when-cross-origin` is not supported, use `no-referrer` policy,
    # no referrer information is sent along with requests.
    referrer_policy:
        enabled: true
        policies:
            - 'no-referrer'
            - 'strict-origin-when-cross-origin'
